namespace app.advertise.DataAccess
{
    internal static class Queries
    {
        internal const string Schema_Adevertisement="advertisement";
        internal const string Schema_Admin = "admins";

        internal const string SP_HoardTyConfig_Ins="advertisement.aoad_hoardtyconfig_ins";
        internal const string SP_HoardTypeMaster_Ins = "advertisement.aoad_hoardingtype_ins";
        internal const string SP_DisplayTypeMaster_Ins = "advertisement.AOAD_DISPLAYTYPE_INS";
        internal const string SP_LocationMaster_Ins = "advertisement.AOAD_LOCATION_INS";

        internal const string List_Active_HoardTypeConfig= $"Select NUM_HOARDINGCONFIG_ID,NUM_HOARDINGCONFIG_HOARDID,NUM_HOARDINGCONFIG_ULBID,VAR_HOARDINGCONFIG_INSBY,DAT_HOARDINGCONFIG_INSDT,VAR_HOARDINGCONFIG_UPDBY,DAT_HOARDINGCONFIG_UPDT,VAR_HOARDINGCONFIG_ACTIVEFLAG from {Schema_Adevertisement}.AOAD_HOARDINGTYPE_CONFIG Where VAR_HOARDINGCONFIG_ACTIVEFLAG='Y'";
        internal const string Single_HoardTypeConfig = "Select Top 1 NUM_HOARDINGCONFIG_ID,NUM_HOARDINGCONFIG_HOARDID,NUM_HOARDINGCONFIG_ULBID,VAR_HOARDINGCONFIG_INSBY,DAT_HOARDINGCONFIG_INSDT,VAR_HOARDINGCONFIG_UPDBY,DAT_HOARDINGCONFIG_UPDT,VAR_HOARDINGCONFIG_ACTIVEFLAG from advertisement.AOAD_HOARDINGTYPE_CONFIG Where NUM_HOARDINGCONFIG_ID={id}";
        internal const string List_HOARDINGTYPE_MST = $"Select NUM_HOARDINGTYPE_ID,VAR_HOARDINGTYPE_NAME,VAR_HOARDINGTYPE_STATUS,VAR_HOARDINGTYPE_INSBY,DAT_HOARDINGTYPE_INSDT,VAR_HOARDINGTYPE_UPDBY,DAT_HOARDINGTYPE_UPDT,VAR_HOARDINGTYPE_IPADDRESS from AOAD_HOARDINGTYPE_MST";
        internal const string Single_HOARDINGTYPE_MST = "Select Top 1 NUM_HOARDINGTYPE_ID,VAR_HOARDINGTYPE_NAME,VAR_HOARDINGTYPE_STATUS,VAR_HOARDINGTYPE_INSBY,DAT_HOARDINGTYPE_INSDT,VAR_HOARDINGTYPE_UPDBY,DAT_HOARDINGTYPE_UPDT,VAR_HOARDINGTYPE_IPADDRESS from AOAD_HOARDINGTYPE_MST Where NUM_HOARDINGTYPE_ID={id}";
        internal const string List_DisplayTYPE_MST = " SELECT NUM_DISPLAYTYPE_ID,VAR_DISPLAYTYPE_NAME,VAR_DISPLAYTYPE_STATUS,VAR_DISPLAYTYPE_INSBY,DAT_DISPLAYTYPE_INSDT,VAR_DISPLAYTYPE_UPDBY,DAT_DISPLAYTYPE_UPDT,VAR_DISPLAYTYPE_IPADDRESS From aoad_displaytype_mst";
        internal const string Single_ById_DisplayTYPE_MST = "SELECT NUM_DISPLAYTYPE_ID,VAR_DISPLAYTYPE_NAME,VAR_DISPLAYTYPE_STATUS,VAR_DISPLAYTYPE_INSBY,DAT_DISPLAYTYPE_INSDT,VAR_DISPLAYTYPE_UPDBY,DAT_DISPLAYTYPE_UPDT,VAR_DISPLAYTYPE_IPADDRESS From aoad_displaytype_mst WHERE NUM_DISPLAYTYPE_ID=:id";
        internal const string List_location_MST = "Select NUM_LOCATION_ULBID,NUM_LOCATION_ID,VAR_LOCATION_NAME,NUM_LOCATION_AREA,NUM_LOCATION_PINCODE,VAR_LOCATION_ACTIVE,VAR_LOCATION_INSBY,DAT_LOCATION_INSDT,VAR_LOCATION_UPDBY,DAT_LOCATION_UPDT,VAR_LOCATION_IPADDRESS,NUM_LOCATION_LATITUDE,NUM_LOCATION_LONGITUDE,NUM_LOCATION_PRABHAGID from aoad_location_mst";
        internal const string Single_ById_location_MST = "Select NUM_LOCATION_ULBID,NUM_LOCATION_ID,VAR_LOCATION_NAME,NUM_LOCATION_AREA,NUM_LOCATION_PINCODE,VAR_LOCATION_ACTIVE,VAR_LOCATION_INSBY,DAT_LOCATION_INSDT,VAR_LOCATION_UPDBY,DAT_LOCATION_UPDT,VAR_LOCATION_IPADDRESS,NUM_LOCATION_LATITUDE,NUM_LOCATION_LONGITUDE,NUM_LOCATION_PRABHAGID from aoad_location_mst Where NUM_LOCATION_ULBID={id}";
        internal const string ModifyStatus_DisplayType_MST = "UPDATE Advertisement.AOAD_DISPLAYTYPE_MST Set VAR_DISPLAYTYPE_STATUS=:VAR_DISPLAYTYPE_STATUS,VAR_DISPLAYTYPE_UPDBY=:VAR_DISPLAYTYPE_UPDBY,DAT_DISPLAYTYPE_UPDT=:DAT_DISPLAYTYPE_UPDT Where NUM_DISPLAYTYPE_ID=:NUM_DISPLAYTYPE_ID";

    }
}
